// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3tVsZmDFLOKu_Ir_fwb9FWVWFw0FIU7U',
    appId: '1:269830646949:web:e064494ba501af499ff14c',
    messagingSenderId: '269830646949',
    projectId: 'prop-app-2a923',
    authDomain: 'prop-app-2a923.firebaseapp.com',
    storageBucket: 'prop-app-2a923.appspot.com',
    measurementId: 'G-HVHN8T24CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIn4PGWe8VW4ayBraRdYhSmBZNCeaMmDI',
    appId: '1:269830646949:android:4e2497f19c828c609ff14c',
    messagingSenderId: '269830646949',
    projectId: 'prop-app-2a923',
    storageBucket: 'prop-app-2a923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrNe_xH8waFaxwBSgVcKhONoNYJmQy46Y',
    appId: '1:269830646949:ios:6e63b59cd9c6b81f9ff14c',
    messagingSenderId: '269830646949',
    projectId: 'prop-app-2a923',
    storageBucket: 'prop-app-2a923.appspot.com',
    iosClientId: '269830646949-ism8s0iegjig7h6ubdr4f8kg3nn66brj.apps.googleusercontent.com',
    iosBundleId: 'com.example.prop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrNe_xH8waFaxwBSgVcKhONoNYJmQy46Y',
    appId: '1:269830646949:ios:6e63b59cd9c6b81f9ff14c',
    messagingSenderId: '269830646949',
    projectId: 'prop-app-2a923',
    storageBucket: 'prop-app-2a923.appspot.com',
    iosClientId: '269830646949-ism8s0iegjig7h6ubdr4f8kg3nn66brj.apps.googleusercontent.com',
    iosBundleId: 'com.example.prop',
  );
}
